package com.tan.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrator generated by hbm2java
 */
//@Entity  错误
//@Table(name = "administrator", catalog = "crm")

@Entity(name = "administrator")
public class Administrator implements java.io.Serializable {

	private String username;
	private String password;

	public Administrator() {
	}

	public Administrator(String username) {
		this.username = username;
	}

	public Administrator(String username, String password) {
		this.username = username;
		this.password = password;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 15)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
