package com.tan.model;
// default package
// Generated 2016-5-2 16:27:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
//@Entity
//@Table(name = "customer", catalog = "crm")
@Entity(name = "customer")
public class Customer implements java.io.Serializable {

	private String id;
	private String name;
	private String sex;
	private String telephone;
	private String email;
	private String address;

	public Customer() {
	}

	public Customer(String id) {
		this.id = id;
	}

	public Customer(String id, String name, String sex, String telephone, String email, String address) {
		this.id = id;
		this.name = name;
		this.sex = sex;
		this.telephone = telephone;
		this.email = email;
		this.address = address;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex", length = 10)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "telephone", length = 45)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
