package com.tan.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
//@Entity
//@Table(name = "employee", catalog = "crm")
@Entity(name = "employee")
public class Employee implements java.io.Serializable {

	private String id;
	private String name;
	private String password;
	private String sex;
	private String telephone;
	private String email;

	public Employee() {
	}

	public Employee(String id, String password) {
		this.id = id;
		this.password = password;
	}

	public Employee(String id, String name, String password, String sex, String telephone, String email) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.sex = sex;
		this.telephone = telephone;
		this.email = email;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "sex", length = 4)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "telephone", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
