package com.tan.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Systeminfo generated by hbm2java
 */
@Entity(name = "systeminfo")
public class Systeminfo implements java.io.Serializable {

	private int idsystemInfo;
	private String systemName;
	private String sysVersion;
	private String person;
	private String email;

	public Systeminfo() {
	}

	public Systeminfo(int idsystemInfo) {
		this.idsystemInfo = idsystemInfo;
	}

	public Systeminfo(int idsystemInfo, String systemName, String sysVersion, String person, String email) {
		this.idsystemInfo = idsystemInfo;
		this.systemName = systemName;
		this.sysVersion = sysVersion;
		this.person = person;
		this.email = email;
	}

	@Id

	@Column(name = "idsystemInfo", unique = true, nullable = false)
	public int getIdsystemInfo() {
		return this.idsystemInfo;
	}

	public void setIdsystemInfo(int idsystemInfo) {
		this.idsystemInfo = idsystemInfo;
	}

	@Column(name = "systemName", length = 40)
	public String getSystemName() {
		return this.systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	@Column(name = "sysVersion", length = 20)
	public String getSysVersion() {
		return this.sysVersion;
	}

	public void setSysVersion(String sysVersion) {
		this.sysVersion = sysVersion;
	}

	@Column(name = "person", length = 20)
	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	@Column(name = "email", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
