package com.tan.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Task generated by hbm2java
 */
//@Entity
//@Table(name = "task", catalog = "crm")
@Entity(name = "task")
public class Task implements java.io.Serializable {

	private Integer idtask;
	private String title;
	private String date;
	private String employeeName;
	private String content;

	public Task() {
	}

	public Task(String title, String date, String employeeName, String content) {
		this.title = title;
		this.date = date;
		this.employeeName = employeeName;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtask", unique = true, nullable = false)
	public Integer getIdtask() {
		return this.idtask;
	}

	public void setIdtask(Integer idtask) {
		this.idtask = idtask;
	}

	@Column(name = "title", length = 40)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "date", length = 20)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "employeeName", length = 20)
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@Column(name = "content", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
